### ISSUE TITLE
Variable dbName needs to be rewritten after assignment to dbDs

### ISSUE THREAD

**Issue by badosu** [Yaribz/SLDB#10]
Migrating system from a `dbName=<dbName>` to a `dbName=DBI:` setting I received the following:

```
20220203123545 - INFO     - [ratingEngine] Creating new partition p202202 in table tsDuelPlayers
20220203123545 - CRITICAL - [ratingEngine] Unable to add partition "p202202" to table tsDuelPlayers (Duplicate partition name p202202)
```

I'm pretty sure this is caused by this query returning 0, even if the value already exists, due to dbName being set in DBI format: https://github.com/badosu/SLDB/blob/5504e2af76061acbcee40a93f2074da58792a471/ratingEngine.pl#L255

I suspect other components might present the same issue

**Comment by Yaribz** [comment]
Good catch, indeed the rating engine and the setup scripts need fix for that.

**Comment by badosu** [comment]
Usually I prefer having a `dbUrl` or could call even `dbDBI` setting with all connection parameters that can be extracted and populated to the individual settings.
