### ISSUE TITLE
Insert games into local SLDB instance

### ISSUE THREAD

**Issue by rosscosack** [Yaribz/SLDB#3]
Hi
Adding allowed games to local instances appears to be undocumented, If the games are to be added with sql can you please advise what format the regex should be? Or, if there is another interface I should be using?
sldbLi.log
```20200114105456 - WARNING  - [SldbLi] Unable to find ratable mod matching host mod, getSkill call from parity_host```
I have tried `Beyond All Reason test-d+-.......` and `~Beyond All Reason test-d+-.......` and `/Beyond All Reason test-d+-......./` and  `Beyond\ All\ Reason\ test-d+-.......`

`modName:~Beyond\ All\ Reason\ test-\d+-.......`

thank you

**Comment by rosscosack** [comment]
I think I found the correct syntax 
`~Beyond\ All\ Reason\ test-d+-.......`
Escape spaces and include tilde

**Comment by rosscosack** [comment]
Hmm, that didn't fix it after all, it's hard to test if it's working

**Comment by Yaribz** [comment]
Hello, the administration of SLDB is far from fully documented unfortunately. The games must indeed be declared manually by inserting rows in the gamesNames tables. Concerning the regex format to use, it is the official MySQL format as described [here](https://dev.mysql.com/doc/refman/8.0/en/regexp.html).

**Comment by rosscosack** [comment]
Can you please provided a valid example of a gamesNames regex string? eg one that works of the official server

**Comment by Yaribz** [comment]
Here is an example for Kernel Panic: "^Kernel Panic [0-9]+\.[0-9]+$"
