### ISSUE TITLE
Table has no partition for value

### ISSUE THREAD

**Issue by rosscosack** [Yaribz/SLDB#4]
I'm getting the error Unable to insert rating for new user 7, period 202001 and type teamFfa in tsT
see version for mysql below and full error details
```
[root@road-flag ~]# mysql --version
mysql  Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
```
Jan 21 10:32:53 road-flag systemd[1]: Started ratingEngine.
Jan 21 10:32:53 road-flag perl[1393]: DBD::mysql::db do failed: Table has no partition for value 202001 at /home/uberserver/builds/SLDB/Sldb.pm line 164.     Jan 21 10:32:53 road-flag perl[1393]: 20200121103253 - NOTICE   - [ratingEngine] Connecting to database DBI:mysql:database=sldb;host=localhost as user sldb   Jan 21 10:32:53 road-flag perl[1393]: 20200121103253 - NOTICE   - [ratingEngine] Initializing trueskill rating environment
Jan 21 10:32:53 road-flag perl[1393]: 20200121103253 - NOTICE   - [ratingEngine] Checking rating database state
Jan 21 10:32:53 road-flag perl[1393]: 20200121103253 - NOTICE   - [ratingEngine] Starting rating queues polling...
Jan 21 10:32:53 road-flag perl[1393]: 20200121103253 - CRITICAL - [ratingEngine] Unable to insert rating for new user 7, period 202001 and type teamFfa in tsTJan 21 10:32:53 road-flag systemd[1]: ratingEngine.service: Main process exited, code=exited, status=1/FAILURE
Jan 21 10:32:53 road-flag systemd[1]: ratingEngine.service: Failed with result 'exit-code'.
```

**Comment by rosscosack** [comment]
I suspect it has something to do with this
https://github.com/Yaribz/SLDB/blob/bb0ec6b614328217caebb22cef419c352767bb0c/Sldb.pm#L483

**Comment by rosscosack** [comment]
Removing the partitioning fixed the issue. I don't fully understand if this is ok to do.
Will I regret this in the future?

**Comment by Yaribz** [comment]
> I suspect it has something to do with this

Yes, this is the part of the code which is responsible for creating the partitions. As you can see it only creates the partitions for years 2012 to 2017. I should update SLDB to perform the partition creation automatically so one wouldn't need to run this maintenance task manually. As a quick fix you can replace "2017" by "2030" in the code you quoted and you should be fine for some time... (if you are creating a new instance of SLDB which won't hold any data prior to 2019 you could also replace "2012" by "2019")

> Removing the partitioning fixed the issue. I don't fully understand if this is ok to do.
> Will I regret this in the future?

Removing partitions will impact performance, which then will degrade with time...
