### ISSUE TITLE
Crash [slMonitor] Unable to find rank of user <id> in accounts table!

### ISSUE THREAD

**Issue by rosscosack** [Yaribz/SLDB#5]
slMonitor is crashing regularly, requires service restart
[slMonitor.log](https://github.com/Yaribz/SLDB/files/4430194/slMonitor.log)
^ refer to recent logs, unable to rank followed by a manual restart when I realize it has crashed

**Comment by Yaribz** [comment]
Did you perform any modification on slMonitor code ?

For some reason it seems your instance of SLDB tries to process game data reports (GDR) containing lobby accounts for which it has no data. This case should only happen when slMonitor isn't online when the game was started, but then SLDB should discard the GDR and not process it...

Also, according to your log it seems your instance of uberserver has the "ghost" user problem and is sending inconsistent commands sometimes.

**Comment by rosscosack** [comment]
hmm, yes I did, I escaped some braces in line 508 since there was a perl notice about it, I had forgotten about that. Have reverted to original

Have also updated uberserver
Thank you
